<?php

namespace AppBundle\Repository;

/**
 * CycleInscritRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CycleInscritRepository extends \Doctrine\ORM\EntityRepository
{
}
