<?php

namespace AppBundle\Repository;

/**
 * SpecialiteInscritRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpecialiteInscritRepository extends \Doctrine\ORM\EntityRepository
{
}
