cursus_index:
    path:     /
    defaults: { _controller: "AppBundle:Cursus:index" }
    methods:  GET

cursus_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Cursus:show" }
    methods:  GET

cursus_new:
    path:     /new
    defaults: { _controller: "AppBundle:Cursus:new" }
    methods:  [GET, POST]

cursus_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Cursus:edit" }
    methods:  [GET, POST]

cursus_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Cursus:delete" }
    methods:  DELETE
