salle_index:
    path:     /
    defaults: { _controller: "AppBundle:Salle:index" }
    methods:  GET

salle_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Salle:show" }
    methods:  GET

salle_new:
    path:     /new
    defaults: { _controller: "AppBundle:Salle:new" }
    methods:  [GET, POST]

salle_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Salle:edit" }
    methods:  [GET, POST]

salle_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Salle:delete" }
    methods:  DELETE
